// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApi.DbContexts;

#nullable disable

namespace RestApi.Migrations
{
    [DbContext(typeof(CityDbContext))]
    [Migration("20231217002835_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RestApi.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The one with that big park.",
                            Name = "New York City"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The one with the big clock.",
                            Name = "London"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The one with the big tower.",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The one with the big fish market.",
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The one with the big opera house.",
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The one with the big wall.",
                            Name = "Beijing"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The one with the big statue.",
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The one with the big mountain.",
                            Name = "Cape Town"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The one with the big square.",
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The one with the big sign.",
                            Name = "Los Angeles"
                        });
                });

            modelBuilder.Entity("RestApi.Entities.Interest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "A 102-story skyscraper located in Midtown Manhattan",
                            Name = "Central Park"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Description = "A 96-meter tall clock tower at the north end of the Palace of Westminster",
                            Name = "Big Ben"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "A giant Ferris wheel on the South Bank of the River Thames",
                            Name = "London Eye"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            Description = "A wrought iron lattice tower on the Champ de Mars",
                            Name = "Eiffel Tower"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "The world's largest art museum and a historic monument",
                            Name = "Louvre Museum"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 4,
                            Description = "A large wholesale market for fish, fruits, and vegetables",
                            Name = "Tsukiji Market"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 4,
                            Description = "A broadcasting and observation tower in Sumida",
                            Name = "Tokyo Skytree"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 5,
                            Description = "A multi-venue performing arts centre at Sydney Harbour",
                            Name = "Sydney Opera House"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 5,
                            Description = "A steel arch bridge across Sydney Harbour",
                            Name = "Sydney Harbour Bridge"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 6,
                            Description = "A series of fortifications built along the historical border of China",
                            Name = "Great Wall of China"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 6,
                            Description = "A palace complex in central Beijing",
                            Name = "Forbidden City"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 7,
                            Description = "An Art Deco statue of Jesus Christ atop Mount Corcovado",
                            Name = "Christ the Redeemer"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 7,
                            Description = "A famous beach in the south zone of Rio de Janeiro",
                            Name = "Copacabana Beach"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 8,
                            Description = "A flat-topped mountain overlooking the city of Cape Town",
                            Name = "Table Mountain"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 8,
                            Description = "An island in Table Bay where Nelson Mandela was imprisoned",
                            Name = "Robben Island"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 9,
                            Description = "A city square in the heart of Moscow",
                            Name = "Red Square"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 9,
                            Description = "A colorful onion-domed church in Red Square",
                            Name = "Saint Basil's Cathedral"
                        },
                        new
                        {
                            Id = 18,
                            CityId = 10,
                            Description = "A landmark sign on Mount Lee",
                            Name = "Hollywood Sign"
                        },
                        new
                        {
                            Id = 19,
                            CityId = 10,
                            Description = "A film studio and theme park in the San Fernando Valley",
                            Name = "Universal Studios Hollywood"
                        });
                });

            modelBuilder.Entity("RestApi.Entities.Interest", b =>
                {
                    b.HasOne("RestApi.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
